import groovy.json.JsonSlurper

node {
    echo "Workspace=${WORKSPACE}"
    echo "User="
    ExecuteShellCommand("whoami", false)

    def dockerImageName = 'java-hello-world'
    def dockerImageNameLatest '${dockerImageName:latest}'
    def dockerRepoServerName = "arvindockerregistry.azurecr.io"
    def baseImageName ="${dockerRepoServerName}/jws31t8:latest"
    def gitRepoUrl = 'https://github.com/arv-devops-test/app-docker-image.git'

    stage('Pre-build Cleanup') {
        CleanWorkspace()
    }

    stage('Get-Git-Repo') {
        git url: gitRepoUrl
    }
    
    stage('Get-Artifacts') {
        //Create a new artifactory server connection instance
        def server = Artifactory.server 'artifactory-main'
  
        // Define what to download from artifactory
        def downloadSpec = """{
        "files": [
            {
                "pattern": "${ArtifactoryWarPath}",
                "flat": "true",
                "target": "ocp/deployments/"
            }
        ]
        }"""

        //Download files defined in downloadspec
        server.download(downloadSpec)
    }
    
    stage('Build and Push Docker Image') {
        def container = BuildDockerImage(dockerImageName)
        // tag as latest

        ExecuteShellCommand("docker tag ${dockerImageName} ${dockerImageNameLatest}", true)
        ExecuteShellCommand("docker push ${dockerImageNameLatest}", true)
        PushDockerImage(container, dockerRepoServerName)
    }

    stage('Post-build Cleanup') {
        
        ExecuteShellCommand("docker image prune -f", false)
        CleanWorkspace()
    }
}

def BuildDockerImage(imageName)
{
    return docker.build(imageName)
}

def PushDockerImage(dockerImage, dockerRepoServerName)
{
    withCredentials([usernamePassword(credentialsId: 'DockerPrivateRegistryId', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {

        ExecuteShellCommand("docker login -u ${USERNAME} -p ${PASSWORD} ${dockerRepoServerName}", true)
        dockerImage.push()
    }
}


def CleanWorkspace()
{
    ws_content = sh (
                    script: "ls",
                    returnStdout: true
                    ).trim()
        echo ws_content
        
        if(ws_content != "")
        {
            echo "Workspace has content:"
            echo "Cleaning workspace..."
            sh 'rm -r $WORKSPACE/* 2>/dev/null';
        }
}

def ExecuteShellCommand(cmd, failOnError) {
   def errorHandling = ""
   if(!failOnError)
   {
       errorHandling = "Ignoring Exit Code as specified"
   }
   try
   {
        exitCode = sh (script: cmd,
                      returnStatus: true)
        
        echo "Finished task with Exit Code: ${exitCode.toString()}  :: ${errorHandling}"
        if(exitCode != 0 && failOnError)
        {
            error("An error occured while executing this: ${cmd}")
        }
   }
   
   catch(ex)
   {
        if(failOnError)
        {
            error("An error occured while executing this: ${cmd}")
        }
   }
   
}
