import groovy.json.JsonSlurper

node {
    echo "Workspace=${WORKSPACE}"
    echo "User="
    ExecuteShellCommand("whoami", false)

    def projectName ="java-hello-world"
    def dockerRepoServerName = "arvindockerregistry.azurecr.io"
    def baseImageName ="${dockerRepoServerName}/jws31t8:latest"
    def gitRepoUrl = 'https://github.com/arv-devops-test/app-docker-image.git'
    def ArtifactoryWarPath = 'java-hello-world/v1/'
    dockerImageName = dockerRepoServerName + "/" + projectName + ":${env.BUILD_ID}"
    dockerImageNameLatest = dockerRepoServerName + "/" + projectName + ":latest"

    stage('Pre-build Cleanup') {
        CleanWorkspace()
    }

    stage('Get-Git-Repo') {
        git url: gitRepoUrl
    }
    
    stage('Get-Artifacts') {
        //Create a new artifactory server connection instance
        def server = Artifactory.server 'arvartifactory'
  
        // Define what to download from artifactory
        def downloadSpec = """{
        "files": [
                {
                    "pattern": "${ArtifactoryWarPath}",
                    "flat": "true",
                    "target": "deploy/"
                }
            ]
        }"""

        //Download files defined in downloadspec
        server.download(downloadSpec)
    }
    
    stage('Build and Push Docker Image') {
        def fullImageName = dockerRepoServerName
        def container = BuildDockerImage(dockerImageName)

        DockerLogin(dockerRepoServerName)
        container.push()
        ExecuteShellCommand("docker tag ${dockerImageName} ${dockerImageNameLatest}", true)
        ExecuteShellCommand("docker push ${dockerImageNameLatest}", true)
    }

    stage('Post-build Cleanup') {
        
        ExecuteShellCommand("docker image prune -f", false)
        CleanWorkspace()
    }
}

def BuildDockerImage(imageName)
{
    return docker.build(imageName)
}

def DockerLogin(dockerRepoServerName)
{
    withCredentials([usernamePassword(credentialsId: 'DockerPrivateRegistryId', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {

        ExecuteShellCommand("docker login -u ${USERNAME} -p ${PASSWORD} ${dockerRepoServerName}", true)
    }
}


def CleanWorkspace()
{
    ws_content = sh (
                    script: "ls",
                    returnStdout: true
                    ).trim()
        echo ws_content
        
        if(ws_content != "")
        {
            echo "Workspace has content:"
            echo "Cleaning workspace..."
            sh 'rm -r $WORKSPACE/* 2>/dev/null';
        }
}

def ExecuteShellCommand(cmd, failOnError) {
   def errorHandling = ""
   if(!failOnError)
   {
       errorHandling = "Ignoring Exit Code as specified"
   }
   try
   {
        exitCode = sh (script: cmd,
                      returnStatus: true)
        
        echo "Finished task with Exit Code: ${exitCode.toString()}  :: ${errorHandling}"
        if(exitCode != 0 && failOnError)
        {
            error("An error occured while executing this: ${cmd}")
        }
   }
   
   catch(ex)
   {
        if(failOnError)
        {
            error("An error occured while executing this: ${cmd}")
        }
   }
   
}
